### ISSUE TITLE
I have added a configuration file (based on data_augmentation_options { of pipeline.config ) for all the options that Augmentation TF API Object Detection core/preprocessor.py

### ISSUE THREAD

**Issue by Leci37** [majrie/visualize_augmentation#4]
Thank you for your work in the open,
I found you here  https://stackoverflow.com/questions/53890669/save-tensorflow-object-detection-augmented-images/55021740#comment137249804_55021740  

I share with you and the community, an improvement version of your code.
I have added a configuration file for all the options that Augmentation TF API (https://github.com/tensorflow/models/blob/master/research/object_detection/core/preprocessor.py ) has. 

So you can give the **N values you want** inside the .yaml  (_based on data_augmentation_options { of pipeline.config_ ),  to the augmentation, and of course keep **all types of augmentations** in TF API Object Detection

The edited code:
```python

# https://github.com/majrie/visualize_augmentation/blob/master/visualize_augmentation.ipynb
# https://github.com/majrie/visualize_augmentation/blob/master/visualize_augmentation.ipynb
# This code is mainly from object detection API jupyter notebook and object detection API preprocessor.py
import json

from object_detection.core import preprocessor
import functools, os
from object_detection import inputs
from object_detection.core import standard_fields as fields
from PIL import Image
import numpy as np
import cv2
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
import yaml
from pathlib import Path

def load_image_into_numpy_array(image):
    (im_width, im_height) = image.size
    return np.array(image.getdata()).reshape(
        (im_height, im_width, 3)).astype(np.float32)  # .astype(np.uint8)


DICT_config = yaml.safe_load(Path("AUG_augmentation_test_2.yaml").read_text())

NUM_REPETED = 1  # lot of augmentations have probabilities < 1 will not happen if repeated only once.
augmented_tensor_dict = None

image2 = Image.open("../igor_2_00173_.jpg")
image_np = load_image_into_numpy_array(image2)

GT_BOXES_FOR_IMG = np.array([[165,172,165+200,172+177],[228,295,228+186,295+171]]) #../igor_2_00173_.jpg"
print(" #CUIDADO si la imagen no es igual por los dos lados ")
GT_BOXES_FOR_IMG = GT_BOXES_FOR_IMG /image_np.shape[0]

image_np = cv2.cvtColor(image_np, cv2.COLOR_RGB2BGR)
# UNCOMMENT THIS CODE TO USE YOUR PICTURE
# IMAGE = "" # add image here
# image2 = Image.open(IMAGE)
save_to_disk = True
DIR_SAVED = '../visualize_augmentation'
PREPROCESING_LIST = [
                        None,
                     (preprocessor.random_horizontal_flip, {}),
                     (preprocessor.random_vertical_flip, {}),
                     (preprocessor.random_rotation90, {}),
                     (preprocessor.random_pixel_value_scale, {}),  # slightly changes the values of pixels
                     (preprocessor.random_image_scale, {}),
                     (preprocessor.random_rgb_to_gray, {}),
                     (preprocessor.random_adjust_brightness, {}),
                     (preprocessor.random_adjust_contrast, {}),
                     (preprocessor.random_adjust_hue, {}),
                     (preprocessor.random_adjust_saturation, {}),
                     (preprocessor.random_distort_color, {}),  # very strong augmentation
                     (preprocessor.random_jitter_boxes, {}),
                     (preprocessor.random_crop_image, {}),
                     (preprocessor.random_pad_image, {}),
                     # (preprocessor.random_absolute_pad_image, {}),  #TypeError: Failed to convert elements of [50, None] to Tensor. Consider casting elements to a supported type. See
                     (preprocessor.random_crop_pad_image, {}),
                     # (preprocessor.random_crop_to_aspect_ratio, {}),  #ValueError: Tried to convert 'params' to a tensor and failed. Error: None values not supported.
                     (preprocessor.random_pad_to_aspect_ratio, {}),
                     (preprocessor.random_black_patches, {}),
                     (preprocessor.random_resize_method, {}),
                     (preprocessor.resize_to_min_dimension, {}),
                     (preprocessor.random_patch_gaussian, {}),
                     (preprocessor.scale_boxes_to_pixel_coordinates, {}),
                     (preprocessor.subtract_channel_mean, {}),
                     # (preprocessor.random_self_concat_image, {}), #ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.
                     # (preprocessor.ssd_random_crop, {}),
                     # (preprocessor.ssd_random_crop_pad, {}), #TypeError: Expected list for 'aspect_ratio_range' argument to 'sample_distorted_bounding_box_v2' Op, not 0.875.
                     # (preprocessor.ssd_random_crop_fixed_aspect_ratio, {}),
                     # (preprocessor.ssd_random_crop_pad_fixed_aspect_ratio, {}),
                     # (preprocessor.convert_class_logits_to_softmax, {}),
                     ]

def draw_rect_with_labels(img, bboxes, class_id,  color=None):#class_dict
    img = img.copy()
    bboxes = bboxes[:, :4]
    bboxes = bboxes.reshape(-1, 4)
    for bbox, label in zip(bboxes, class_id):
        pt1, pt2 = (bbox[0], bbox[1]), (bbox[2], bbox[3])
        pt1 = int(pt1[0]), int(pt1[1])
        pt2 = int(pt2[0]), int(pt2[1])
        class_name = "xxx" #class_dict[label]['name']
        ((text_width, text_height), _) = cv2.getTextSize(class_name, cv2.FONT_HERSHEY_SIMPLEX, 0.35, 1)
        img = cv2.rectangle(img.copy(), pt1, pt2, color, int(max(img.shape[:2]) / 200))
        img = cv2.putText(img.copy(), class_name, (int(bbox[0]), int(bbox[1]) - int(0.3 * text_height)),
                          cv2.FONT_HERSHEY_SIMPLEX, fontScale=1, color=(255, 255, 255), lineType=cv2.LINE_AA)
    return img

if not os.path.exists(DIR_SAVED):
    os.makedirs(DIR_SAVED)

for preprocessing_technique in PREPROCESING_LIST:
    for i in range(NUM_REPETED):

        tf.compat.v1.reset_default_graph()
        if preprocessing_technique is not None:
            name_tech = str(preprocessing_technique[0].__name__)
            print(str(preprocessing_technique[0].__name__))
            data_augmentation_options = [preprocessing_technique]

            if name_tech in DICT_config :
                if DICT_config[name_tech] is None:
                    DICT_config[name_tech] = {}
                    print("DEBUG El fichero .yaml no tiene valor por defectom \tKey: ",name_tech )
                print("La key existe en el fichero .yaml  \tKey:", name_tech, "\t", DICT_config[name_tech])
                data_augmentation_options[0]  = (data_augmentation_options[0][0] ,  DICT_config[name_tech] )
            else:
                print("WARN la key NO existe en el fichero .yaml  Key:",name_tech )
        else:
            print('Image without augmentation: ')
            data_augmentation_options = []
            continue # TODO remove ¿?

        data_augmentation_fn = functools.partial(
            inputs.augment_input_data,
            data_augmentation_options=data_augmentation_options)

        Tensor_dict = {
            fields.InputDataFields.image:
                tf.constant(image_np.astype(np.float32)),
            fields.InputDataFields.groundtruth_boxes:
                tf.constant(np.array(GT_BOXES_FOR_IMG, np.float32)),
            fields.InputDataFields.groundtruth_classes:
                tf.constant(np.array([1.0, 1.0], np.float32)),
        }
        augmented_tensor_dict = data_augmentation_fn(tensor_dict=Tensor_dict)
        with tf.compat.v1.Session()  as sess:
            augmented_tensor_dict_out = sess.run(augmented_tensor_dict)

        if preprocessing_technique is not None:
            img_aug_np = augmented_tensor_dict_out[fields.InputDataFields.image]
            gt_boxes = augmented_tensor_dict_out[fields.InputDataFields.groundtruth_boxes]
            gt_classes = augmented_tensor_dict_out[fields.InputDataFields.groundtruth_classes]
            path_saved = DIR_SAVED + '/aug_' + str(preprocessing_technique[0].__name__) + '_' + str(i) + '.png'
            path_saved = path_saved.replace('ramdom', "ram")
            print(path_saved,"\tShape: ", img_aug_np.shape,"\tgt_boxes: ", gt_boxes , "\tgt_classes:" ,gt_classes,"\n")
            cv2.imwrite(path_saved, img_aug_np)

            np_img_with_box_check = draw_rect_with_labels(img=img_aug_np,bboxes=gt_boxes *640 ,class_id=gt_classes,color=(255, 0, 0))
            cv2.imwrite(path_saved.replace(".png", "_boxes.png"), np_img_with_box_check)

```
![image](https://github.com/majrie/visualize_augmentation/assets/110530848/d6e909b0-00ef-4eff-b969-b38835602351)

The file with the .yaml values: (inspirated in https://stackoverflow.com/questions/44906317/what-are-possible-values-for-data-augmentation-options-in-the-tensorflow-object )

```yaml
normalize_image :
  original_minval: 0.0,
  original_maxval: 255.0
  target_minval: -1.0
  target_maxval: 1.0

random_horizontal_flip :
  keypoint_flip_permutation: 1
  keypoint_flip_permutation: 0
  keypoint_flip_permutation: 2
  keypoint_flip_permutation: 3
  keypoint_flip_permutation: 5
  keypoint_flip_permutation: 4
  probability: 0.5

random_vertical_flip :
  keypoint_flip_permutation: 1
  keypoint_flip_permutation: 0
  keypoint_flip_permutation: 2
  keypoint_flip_permutation: 3
  keypoint_flip_permutation: 5
  keypoint_flip_permutation: 4
  probability: 0.5

random_rotation90 :
  keypoint_rot_permutation: 3
  keypoint_rot_permutation: 0
  keypoint_rot_permutation: 1
  keypoint_rot_permutation: 2
  probability: 0.5

random_pixel_value_scale :
  minval: 0.8
  maxval: 1.2

random_image_scale :
   min_scale_ratio: 0.8
   max_scale_ratio: 2.2

random_rgb_to_gray :
   probability: 0.8

random_adjust_brightness :
   max_delta: 0.2

random_adjust_contrast :
   min_delta: 0.7
   max_delta: 1.1

random_adjust_hue :
   max_delta: 0.01

random_adjust_saturation :
   min_delta: 0.75
   max_delta: 1.15

random_distort_color :
   color_ordering: 1

random_jitter_boxes :
   ratio: 0.1
   jitter_mode: shrink

random_crop_image :
   min_object_covered: 0.75
#   min_aspect_ratio: 0.75
#   max_aspect_ratio: 1.5
#   min_area: 0.25
#   max_area: 0.875
   aspect_ratio_range : [0.75, 1.33]
   area_range : [0.1, 1.0]
   overlap_thresh: 0.5
   clip_boxes: False
   random_coef: 0.125

random_pad_image :

random_absolute_pad_image :
   max_height_padding: 50
   max_width_padding: 50

random_crop_pad_image :
   min_object_covered: 0.75
#   min_aspect_ratio: 0.75
#   max_aspect_ratio: 1.5
#   min_area: 0.25
#   max_area: 0.875
   overlap_thresh: 0.5
   clip_boxes: False
   random_coef: 0.125
   aspect_ratio_range : [0.75, 1.5]
   area_range : [0.1, 1.0]

random_crop_pad_image :
   min_object_covered: 0.75
   overlap_thresh: 0.5
   clip_boxes: False
   random_coef: 0.125
   aspect_ratio_range: [ 0.75, 1.5 ]
   area_range: [ 0.1, 1.0 ]
   min_padded_size_ratio: [ 0.5, 0.75]
   max_padded_size_ratio: [ 0.5, 0.75]


random_crop_to_aspect_ratio :
   aspect_ratio: 0.85
   overlap_thresh: 0.35
#   clip_boxes: True

random_black_patches :
   max_black_patches: 20
   probability: 0.95
   size_to_image_ratio: 0.12

random_jpeg_quality :
   random_coef: 0.5
   min_jpeg_quality: 40
   max_jpeg_quality: 90

random_downscale_to_target_pixels :
   random_coef: 0.5
   min_target_pixels: 200
   max_target_pixels: 900

random_patch_gaussian :
   random_coef: 0.5
   min_patch_size: 10
   max_patch_size: 300
   min_gaussian_stddev: 0.2
   max_gaussian_stddev: 1.5

subtract_channel_mean:
   means : [11.1,11.1,11.1]

autoaugment_image :
   policy_name: 'v0'

drop_label_probabilistically:
   label: 2
   drop_probability: 0.5

remap_labels:
   original_labels: 1
   original_labels: 2
   new_label: 3

random_resize_method :
   target_size : [75,100]
#   target_height: 75
#   target_width: 100

resize_image :
   new_height: 75
   new_width: 100
   method: BICUBIC

random_self_concat_image :
   concat_vertical_probability: 0.5
   concat_horizontal_probability: 0.25
#   label_weights: 0.5

ssd_random_crop :
  - operations :
     min_object_covered: 0.0
     min_aspect_ratio: 0.875
     max_aspect_ratio: 1.125
     min_area: 0.5
     max_area: 1.0
     overlap_thresh: 0.0
     clip_boxes: False
     random_coef: 0.375
  - operations :
     min_object_covered: 0.25
     min_aspect_ratio: 0.75
     max_aspect_ratio: 1.5
     min_area: 0.5
     max_area: 1.0
     overlap_thresh: 0.25
     clip_boxes: True
     random_coef: 0.375

ssd_random_crop :

ssd_random_crop_pad :
#  - operations :
       min_object_covered: [0.1,  0.7]
#       min_aspect_ratio: 0.875
#       max_aspect_ratio: 1.125
       aspect_ratio_range: [0.875,  1.125]
#       min_area: 0.5
#       max_area: 1.0
       area_range : [0.5, 1.0]
       overlap_thresh: [ 0.3,  0.9]
       clip_boxes:  [False,False]
       random_coef: [ 0.375 ]
       min_padded_size_ratio: [ 1.0, 1.0 ]
       max_padded_size_ratio: [ 2.0, 2.0 ]
       pad_color : [0.5,0.5,0.5]
#       pad_color_r: 0.5
#       pad_color_g: 0.5
#       pad_color_b: 0.5
#  - operations :
#       min_object_covered: 0.25
#       min_aspect_ratio: 0.75
#       max_aspect_ratio: 1.5
#       min_area: 0.5
#       max_area: 1.0
#       overlap_thresh: 0.25
#       clip_boxes: True
#       random_coef: 0.375
#       min_padded_size_ratio: [ 1.0, 1.0 ]
#       max_padded_size_ratio: [ 2.0, 2.0 ]
#       pad_color_r: 0.5
#       pad_color_g: 0.5
#       pad_color_b: 0.5

ssd_random_crop_fixed_aspect_ratio :
#  - operations :
  min_object_covered: 0.0
  #     min_area: 0.5
  #     max_area: 1.0
  area_range : [0.5, 1.0]
  overlap_thresh: 0.0
  clip_boxes: False
  random_coef: 0.375
#  - operations :
#     min_object_covered: 0.25
#     min_area: 0.5
#     max_area: 1.0
#     overlap_thresh: 0.25
#     clip_boxes: True
#     random_coef: 0.375
#     aspect_ratio: 0.875


ssd_random_crop_pad_fixed_aspect_ratio :
  min_object_covered: [ 0.1,  0.7 ]
  #       min_aspect_ratio: 0.875
  #       max_aspect_ratio: 1.125
  aspect_ratio_range: [ 0.875,  1.125 ]
  #       min_area: 0.5
  #       max_area: 1.0
  area_range: [ 0.5, 1.0 ]
  overlap_thresh: [ 0.3,  0.9 ]
  clip_boxes: [ False,False ]
  random_coef: [ 0.375 ]
  min_padded_size_ratio: [ 1.0, 1.0 ]
  max_padded_size_ratio: [ 2.0, 2.0 ]
#  - operations :
#     min_object_covered: 0.0
#     min_aspect_ratio: 0.875
#     max_aspect_ratio: 1.125
#     min_area: 0.5
#     max_area: 1.0
#     overlap_thresh: 0.0
#     clip_boxes: False
#     random_coef: 0.375
#  - operations :
#     min_object_covered: 0.25
#     min_aspect_ratio: 0.75
#     max_aspect_ratio: 1.5
#     min_area: 0.5
#     max_area: 1.0
#     overlap_thresh: 0.25
#     clip_boxes: True
#     random_coef: 0.375
#  - aspect_ratio: 0.875
#  - min_padded_size_ratio: [ 1.0, 1.0 ]
#  - max_padded_size_ratio: [ 2.0, 2.0 ]

convert_class_logits_to_softmax :
   temperature: 2

random_square_crop_by_scale :
   scale_min: 0.25
   scale_max: 2.0
   num_scales: 8


adjust_gamma :
   gamma: 2.2
   gain: 2.0

```
